name: EventHub Playwright CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox]

    env:
      BASE_URL: https://eventhub.rahulshettyacademy.com
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

  
      - name: Run Smoke Tests (PR)
        if: github.event_name == 'pull_request'
        run: npm run test:smoke -- --project=${{ matrix.browser }}

      - name: Run Regression Tests (Push)
        if: github.event_name != 'pull_request'
        run: npm run test:regression -- --project=${{ matrix.browser }}

      - name: Generate Allure Report
        if: always()
        run: npm run report:allure

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report-${{ matrix.browser }}
          path: reports/html-report/

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.browser }}
          path: allure-report/